travis:
  secure:
    BINSTAR_TOKEN: HGXqReqnOHwFrL2zXIgO2EW2SjMBNaIWQRdzZIxl8G9FBeB0c/3NiT2tjJxfh1yUsjBtuZjETOFwf7RFpOX0bpM/p2j7OHVyNusSZtHXG61C69CzXb61Hp+GrXHGf4oId1rk8S7sKHO8pKvEQyv5tLUOM8btN14CPw5NKT33rzGDKxiqt7rooOiu91jz0vQ5mhFx9mANDddVK14u51VE48kwZOLMafSWE9Pj5eec4vRdX4QE7zwfy+RlO0p6cS2l2Im8qx9I+5hMj8YYN9m3qivHAGFzlq4HlP8+x5BZlNc3ML2FaA1wzJYEdvPYNF+TzDvCtmfElyDhEJa9YaaPxnSNxl9WCbOS+Eu7cPddNJ14zdME6F84g//roSjR46CGA0JmMvb4VsPj0B4MXWUsSSI1ahcEPAiDHlKOVOFf8gOcb0Sg4TYwCkwGQgaH4vTSNR45zKeLoFQfyQGDC/NYVrOKdNc5QjEq/62HI7tz3iCovcBRze4kQSYqT/FPy8cx3MeP9BxJuDwejkhEZecUWUZbmloZwvD7Xh6eSYWIRSb51uDPKdPYGsPJJJzG/hp67u5PkCFU/ydbsU0JdGNHKnawL4lNI4McZsp9xMuiAZ4uvD/JoBWo7Pfqd9jQQ9uIhfMWHOcl+pHnBBSQQ72ueFMDGA4kQ8NgIBz7VYEn+hE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
